name: firebase_article
description: "Firebase article help setup blog articles in firebase firestore and storage.
              In order to make firebase_article functional, the architecture of the firebase
              firestore and cloud storage should be the following:
              
              - firestore: 
              [article_collection_name]/[article_name]/{
                                                        'id':article_name,
                                                        'title':title,
                                                        'content':content.md,
                                                        'releaseDate':2024-05-08,
                                                        'relations':[
                                                                      {
                                                                        'cover_image':cover_image.jpg
                                                                      }
                                                                    ]
                                                        } 
                Here:
                  - [article_collection_name] is the name of the collection where articles are stored.
                      It should be provided in [ArticleRepository] as collection argument if different from 'articles'.
                  - [article_name] is the id of the article and the name of the doc in firestore for the article.
                  - [relations] is an array that handle all optional metadata relative to the article like: (here) the
                    cover image of the article, or a list of related articles, or the article author.
                  - content.md, cover_image.jpg are files stored in cloud storage as follow:

              - cloud Storage:
              [article_collection_name]
                - [article_name]/
                  - content.md
                  - cover_image.jpg
                  - ...
                "
version: 1.1.2
homepage: none

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  json_annotation: ^4.8.1
  markdown_widget: ^2.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_cloud_firestore: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
